# Generated by Django 3.0.4 on 2020-07-02 14:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_api', '0002_auto_20200702_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='activityperiod',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_zone',
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='activity_period',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='time_zone',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
